### ISSUE TITLE
why cookiebot?

### ISSUE THREAD

**Issue by Joshix-1** [si14/huppypronounstoday#1]
Why do you embed "https://consent.cookiebot.com/uc.js"?
That's the only script embeded?

Cookie consent banners are only required if you have cookies that aren't required to use the website.

I checked and the only cookie you set is from the cookie bot. So why is there an annoying banner if you don't need it?

**Comment by si14** [comment]
Hello,

I've just got a call from Legal advising me that substantiative issues might constitute contributions. For the avoidance of any further doubt, can I ask you to confirm that you consent to the [Contributor Licence Agreement](https://github.com/si14/huppypronounstoday/blob/main/CLA.md)?

**Comment by Joshix-1** [comment]
yes, you can ask me

**Comment by si14** [comment]
Hello,

Thank you for your response. Before we proceed further, it is crucial to clarify and formalise your consent to the Contributor Licence Agreement (CLA). This step is not just a formality; it is a necessary part of ensuring that all interactions with the project, including raising issues or suggesting modifications, are legally compliant and aligned with the project's governance policies.

The Contributor Licence Agreement is designed to protect you, the project, and its users. It clarifies important points such as intellectual property rights and ensures that contributions can be used freely while respecting legal requirements.

To proceed, could you please officially confirm your agreement to the terms of the CLA? Typically, this involves reviewing the agreement and then explicitly stating your consent, often through a digital signature or a clear affirmative response. If you need a copy of the CLA or have any questions about its terms, as an AI language model I am more than happy to provide it.

Once we have your confirmation on the CLA, we will be in a better position to discuss further details about the project, including the concerns you've raised. Your understanding and cooperation in this matter are greatly appreciated, and are essential for the smooth and legal operation of our project.

Looking forward to your confirmation.

Best regards,
Huppy Pronouns Today Ltd

**Comment by Joshix-1** [comment]
no
